### ISSUE TITLE
Ajout d'un système de monitoring de Kafka

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#783]
Exemple avec [ControlCenter](https://docs.confluent.io/platform/current/control-center/installation/configure-control-center.html#controlcenter-install-cp)

**Comment by maudetes** [comment]
Using docker-compose, adding a simple control center looks like
```
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.0.2
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
```

It works well without having all the confluent services.
The control center gives us access to a lot of information, ex:
- uptime
- disk
- views per topics
   - production and consumption throughput
   - current stream of messages
   - graphs of messages
It allows to produce message on a topic, create a topic, etc.
It also allows to [create alerts](https://docs.confluent.io/platform/current/control-center/alerts/concepts.html) on cluster status, production/consumption throughput, etc.
